{
 "title": "NASA API - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request rate (per route)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "{{method}} {{endpoint}}" }
   ]
  },
  {
   "title": "Avg latency (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Pods up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(up{job=~\"nasa-api.*|\"})"
    }
   ]
  }
 ]
}