grafana:
  enabled: true
  adminPassword: "${GRAFANA_ADMIN_PASSWORD}"
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
    datasources:
      enabled: true
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
additionalPrometheusRulesMap: {}
additionalDataSources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus-operated.monitoring.svc.cluster.local:9090
    access: proxy
    isDefault: true