apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-api
  labels:
    app: nasa-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nasa-api
  template:
    metadata:
      labels:
        app: nasa-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: nasa-api
        image: <ECR_REPO_URI>/nasa-api:latest
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: NASA_API_KEY
          valueFrom:
            secretKeyRef:
              name: nasa-secret
              key: api-key
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
