apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nasa-api-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nasa-api
  namespaceSelector:
    any: false
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s